spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 161718
    url: jdbc:mysql://localhost:3306/recipe_sharing_yt
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
